language: java
install: true

# os: linux
# dist: trusty
jdk: 
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - oraclejdk14
  - oraclejdk15

#script:
#  - bundle exec gradle build --scan -s